### ISSUE TITLE
Background tracking

### ISSUE THREAD

**Issue by juanjomendezhealios** [OSUPCVLab/mobile-ar-sensor-logger#25]
Hi! I've found your application really interesting and I would like to start working with this project to collect data form my own device. But first, I like to ask you about some things before starting working:

1. Is it possible to track at 50 Hz for the IMU? I would like to reduce the frequency in order to get more information.

2. Is the application working in background? With this I mean that the process of tracking the sensors do not stop due to sending the application to background instead of being all the time in foreground.

Thank in advance and congratulations for this work!

**Comment by JzHuai0108** [comment]
Thank you for your interest in the app.
1. The IMU logging frequency can be adjusted in the settings panel.
2. This is a good question. I recall that for both the android and the ios app, I intentionally made it possible to log IMU data at background. For android, this is done by continuing logging in onStop(). For ios, this is done with [suggestions from here](https://stackoverflow.com/questions/10674004/ios-keep-application-running-in-background).
But I am not sure if it is possible to log the image stream in background since I have not thoroughly tested it. Another reason is that I don't see the benefit of logging images in background.
That said, I am curious if you are doing a project that does not need to log images. If this is the case, then probably some other apps that do not log images may be more suitable, e.g., the getSensorData app.
On the other hand, I am thinking to add the feature "logging images in background" to the app, but I am too busy (in making a living :) ) to do so at the moment.
