### ISSUE TITLE
Number of frames in the video 0.0 disagrees with the length of the provided timestamps 369

### ISSUE THREAD

**Issue by varun3108** [OSUPCVLab/mobile-ar-sensor-logger#5]
I am using Samsung M31 and the movie.mp4 that I am getting from the app that is being used to create rosbag is giving me this error. How to fix this?

Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
given video time offset 0.0
Loaded 369 timestamps for frames
video frame rate 0.0
#Frames 0.0 in the video /home/mindbeat/vf/movie.mp4
Traceback (most recent call last):
  File "/home/mindbeat/vio_common/python/kalibr_bagcreater.py", line 511, in <module>
    main()
  File "/home/mindbeat/vio_common/python/kalibr_bagcreater.py", line 418, in main
    shift_in_time=parsed.shift_secs)
  File "/home/mindbeat/vio_common/python/kalibr_bagcreater.py", line 301, in write_video_to_rosbag
    len(frame_timestamps)))
Exception: Number of frames in the video 0.0 disagrees with the length of the provided timestamps 369

**Comment by JzHuai0108** [comment]
I believe the cause is in the line
"Failed to load Python extension for LZ4 support. LZ4 compression will not be available."
The direct result of the cause is the line
"#Frames 0.0 in the video /home/mindbeat/vf/movie.mp4". That is, the python script fails to load the video file.
With a brief googling on this issue "Failed to load Python extension for LZ4 support", 
I think there is [something wrong with your python environment](https://github.com/RobotWebTools/rosbridge_suite/issues/384).
Try another computer if possible.
