### ISSUE TITLE
Pixel alignment issues

### ISSUE THREAD

**Issue by anastasiia-kornilova** [OSUPCVLab/mobile-ar-sensor-logger#6]
Dear authors, thank you for such a useful app! That is what every sensors lab dreams about.

Investigating your code and paper, I don't understand the thought about the disadvantages of using ImageReader and MediaCodec together; using GL and MediaMuxer seems to be overwhelmed because it generates additional load on the processor in comparison to optimized MediaRecorder. In the paper, there is a statement, "To efficiently display the camera frames on the screen, the GLSurfaceView is used for rendering. Additionally, it shares the rendered frame with a MediaCodec encoder, thus avoiding the pixel alignment issues which arise in using ImageReader and MediaCodec together." Could you give more explanations on what is "pixel alignment issues"?

**Comment by JzHuai0108** [comment]
We have considered several approaches to efficiently display and record images. The below are my notes in developing the program. It deserves space in the submitted paper.

Methods to save camera frames in Android
1. OpenCV4Android: hard to get image timestamps
2. Camera API: Camera PreviewCallback, onPreviewFrame, are deprecated.

For camera2 API, 
| camera 2 API | camera characteristics and image timestamps |    Efficiently record frames |  Coding complexity  |
|----------------------------|-----------------------------------|----------------------------------|-------------------------------------------|
| 3. MediaRecorder   |                  No, interfaces are limited                   |   Yes                               |  Low        |
| 4. ImageReader + framewise saving |  Yes             | Not efficient, ~15Hz on $400 Honor v10   |   Low              |
| 5. ImageReader + MediaCodec + MediaMuxer |   Yes |  Yes  | High |
| 6. GLSurfaceView + MediaCodec + MediaMuxer | Yes  | Yes  | Medium |

For approach 5, the coding is highly complex because it is error prone to fiddle with chroma planes, for instance, COLOR_FormatYUV420Flexible may be used by MediaCodec while YUV_420_888 is used by ImageReader. 
See [issue1](https://stackoverflow.com/questions/18795353/using-mediacodec-to-save-series-of-images-as-video) and [issue2](https://stackoverflow.com/questions/13703596/mediacodec-and-camera-colorspaces-dont-match).

I hope you can see why we choose approach 6 in implementing the android variant of the MARS logger and what we mean by the pixel alignment issue in using ImageReader and MediaCodec together.

**Comment by anastasiia-kornilova** [comment]
@JzHuai0108 , yes, now your solution is absolutely clear. Thank you for such a detailed explanation!
